version: '3.7'
services:
  web:
    image: nginx
    ports:
      - "6001:80"
    links:
      - php
      - db
    volumes:
      - ./nginx/www/wordpress:/usr/share/nginx/html
      - ./nginx/conf/wordpress:/etc/nginx/conf.d/default.conf
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - "3306:3306"    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "6002:80"
    links:
      - db
  php:
    build: ./php
    volumes:
      - ./nginx/www/wordpress:/usr/share/nginx/html

